### PR TITLE
feat(readme) init

### PR DESCRIPTION
**Pull request by nothingismagick**
Just the facts. And a picture. With a few links. And thankyous. And a license or three.

### CODE REVIEW

**Comment by Momics** [comment]
Investigating the Tauri v2 source code and examples for handling re-spinning killed processes that listen on the network for iOS and Android. Specifically looking into issues with TCP connections becoming unreachable after the app goes into the background and is reopened.

**Comment by Momics** [comment]
I'm investigating the Tauri v2 source code and examples for handling re-spinning killed processes that listen on the network, particularly for iOS and Android. I have encountered an issue where a TCP connection becomes unreachable after the app goes into the background, the screen locks, and the app is reopened. Any insights or relevant code snippets would be greatly appreciated!

**Comment by j4rviscmd** [comment]
dummy

**Comment by j4rviscmd** [comment]
Please delete this comment

**Pull request merged**
